name: Eval & Regression

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  eval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests & evals
        run: |
          pytest -q || true
          python eval/run_evals.py || true
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: eval-results
          path: results/